import '../../styles/globals.css'
import '../../styles/variable.css'
import '../../assests/fonts/Poppins/stylesheet.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
